# Generated by Django 5.2.8 on 2025-11-24 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gewalttat',
            fields=[
                ('tat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tat_alter', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=2, verbose_name='Alter zum Tatzeitpunkt (JA/NEIN/KA)')),
                ('tat_zeitraum', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=2, verbose_name='Tatzeitraum (JA/NEIN/KA)')),
                ('tat_anzahl_vorfaelle', models.CharField(choices=[('E', 'einmalig'), ('M', 'mehrere'), ('G', 'genaue Zahl'), ('K', 'keine Angabe')], max_length=2, verbose_name='Anzahl Vorfälle')),
                ('tat_anzahl_taeter_innen', models.CharField(choices=[('1', '1'), ('M', 'mehrere'), ('G', 'genaue Zahl'), ('K', 'keine Angabe')], max_length=2, verbose_name='Anzahl Täter:innen')),
                ('tat_art', models.CharField(max_length=1024, verbose_name='Art der Gewalt (Mehrfachauswahl/Text)')),
                ('tatort', models.CharField(choices=[('L', 'Leipzig'), ('LL', 'Leipzig Land'), ('NS', 'Nordsachsen'), ('S', 'Sachsen'), ('D', 'Deutschland'), ('A', 'Ausland'), ('F', 'auf der Flucht'), ('H', 'im Herkunftsland'), ('K', 'keine Angabe')], max_length=2, verbose_name='Tatort')),
                ('tat_anzeige', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('E', 'noch nicht entschieden'), ('K', 'keine Angabe')], max_length=2, verbose_name='Anzeige')),
                ('tat_medizinische_versorgung', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=2, verbose_name='Medizinische Versorgung')),
                ('tat_spurensicherung', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=2, verbose_name='Vertrauliche Spurensicherung')),
                ('tat_mitbetroffene_kinder', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mitbetroffene Kinder')),
                ('tat_direktbetroffene_kinder', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Direkt betroffene Kinder')),
                ('tat_notizen', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Gewalttat',
                'verbose_name_plural': 'Gewalttaten',
            },
        ),
        migrations.CreateModel(
            name='KlientIn',
            fields=[
                ('klient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('klient_rolle', models.CharField(choices=[('B', 'Betroffene:r'), ('A', 'Angehörige:r'), ('F', 'Fachkraft')], max_length=2, verbose_name='Rolle')),
                ('klient_alter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Alter (Jahre)')),
                ('klient_geschlechtsidentitaet', models.CharField(choices=[('CW', 'cis weiblich'), ('CM', 'cis männlich'), ('TW', 'trans weiblich'), ('TM', 'trans männlich'), ('TN', 'trans nicht-binär'), ('I', 'inter'), ('A', 'agender'), ('D', 'divers'), ('K', 'keine Angabe')], max_length=2, verbose_name='Geschlechtsidentität')),
                ('klient_sexualitaet', models.CharField(choices=[('L', 'lesbisch'), ('S', 'schwul'), ('B', 'bisexuell'), ('AX', 'asexuell'), ('H', 'heterosexuell'), ('K', 'keine Angabe')], max_length=2, verbose_name='Sexualität')),
                ('klient_wohnort', models.CharField(choices=[('LS', 'Leipzig Stadt'), ('LL', 'Leipzig Land'), ('NS', 'Nordsachsen'), ('S', 'Sachsen (Andere)'), ('D', 'Deutschland (Andere)'), ('A', 'Ausland'), ('K', 'keine Angabe')], max_length=2, verbose_name='Wohnort')),
                ('klient_staatsangehoerigkeit', models.CharField(max_length=100, verbose_name='Staatsangehörigkeit')),
                ('klient_beruf', models.CharField(max_length=255, verbose_name='Beruf')),
                ('klient_schwerbehinderung', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Schwerbehinderung')),
                ('klient_schwerbehinderung_detail', models.TextField(blank=True, help_text='Nur ausfüllen, wenn Schwerbehinderung: Ja', verbose_name='Form/Grad der Behinderung')),
                ('klient_kontaktpunkt', models.CharField(max_length=255, verbose_name='Kontaktpunkt (Quelle)')),
                ('klient_dolmetschungsstunden', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dolmetschungsstunden')),
                ('klient_dolmetschungssprachen', models.CharField(blank=True, max_length=255, verbose_name='Dolmetschungssprachen')),
                ('klient_notizen', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Klient:in',
                'verbose_name_plural': 'Klient:innen',
            },
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('vorname_mb', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname_mb', models.CharField(max_length=100, verbose_name='Nachname')),
                ('mail_mb', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail')),
                ('rolle_mb', models.CharField(choices=[('B', 'Basis'), ('E', 'Erweiterung'), ('AD', 'Admin')], default='B', max_length=2, verbose_name='Rolle')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzerkonto',
                'verbose_name_plural': 'Benutzerkonten',
            },
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('fall_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mitarbeiterin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zuständige Mitarbeiter:in')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.klientin', verbose_name='Zugeordnete Klient:in')),
            ],
            options={
                'verbose_name': 'Fall',
                'verbose_name_plural': 'Fälle',
            },
        ),
        migrations.CreateModel(
            name='Beratungstermin',
            fields=[
                ('beratungs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('beratungsstelle', models.CharField(choices=[('LS', 'Fachberatung Leipzig Stadt'), ('NS', 'Nordsachsen'), ('LL', 'Landkreis Leipzig')], max_length=2, verbose_name='Beratungsstelle')),
                ('anzahl_beratungen', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl Beratungen')),
                ('termin_beratung', models.DateField(verbose_name='Datum des Beratungstermins')),
                ('beratungsart', models.CharField(choices=[('P', 'persönlich'), ('V', 'Video'), ('T', 'Telefon'), ('A', 'aufsuchend'), ('S', 'schriftlich')], max_length=2, verbose_name='Durchführungsart')),
                ('notizen_beratung', models.TextField(blank=True, verbose_name='Notizen')),
                ('berater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Berater:in')),
                ('fall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beratungstermine', to='api.fall', verbose_name='Zugeordneter Fall')),
            ],
            options={
                'verbose_name': 'Beratungstermin',
                'verbose_name_plural': 'Beratungstermine',
            },
        ),
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('anfrage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anfrage_weg', models.CharField(max_length=100, verbose_name='Anfrageweg (Freitext)')),
                ('anfrage_datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum der Anfrage')),
                ('anfrage_ort', models.CharField(choices=[('LS', 'Leipzig Stadt'), ('LL', 'Leipzig Land'), ('NS', 'Nordsachsen'), ('S', 'Sachsen (Andere)'), ('D', 'Deutschland (Andere)'), ('A', 'Ausland'), ('K', 'keine Angabe')], max_length=2, verbose_name='Anfrage Ort')),
                ('anfrage_person', models.CharField(choices=[('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('B', 'Betroffene:r'), ('AN', 'anonym'), ('qB', 'queer Betroffene:r'), ('qF', 'queer Fachkraft'), ('qA', 'queer Angehörige:r'), ('qAN', 'queer anonym'), ('FfB', 'Fachkraft für Betroffene'), ('AfB', 'Angehörige:r für Betroffene'), ('FFqB', 'Fachkraft für queere Betroffene'), ('AfqB', 'Angehörige:r für queere Betroffene')], max_length=4, verbose_name='Anfrage Person (wer)')),
                ('anfrage_art', models.CharField(choices=[('MS', 'medizinische Soforthilfe'), ('VS', 'vertrauliche Spurensicherung'), ('B', 'Beratungsbedarf'), ('R', 'rechtliche Fragen'), ('S', 'Sonstiges')], max_length=2, verbose_name='Anfrage Art')),
                ('mitarbeiterin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zuständige Mitarbeiter:in')),
                ('beratungstermin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.beratungstermin', verbose_name='Zugeordneter Beratungstermin')),
                ('fall', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ursprung_anfrage', to='api.fall', verbose_name='Zugeordneter Fall')),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
            },
        ),
        migrations.CreateModel(
            name='Gewaltfolge',
            fields=[
                ('gewalttat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.gewalttat', verbose_name='Zugeordnete Gewalttat')),
                ('psychische_folgen', models.CharField(choices=[('D', 'Depression'), ('A', 'Angststörung'), ('PT', 'PTBS'), ('B', 'Burn-out'), ('S', 'Schlafstörungen'), ('SU', 'Sucht'), ('K', 'Kommunikationsschwierigkeiten'), ('V', 'Vernachlässigung alltäglicher Dinge'), ('N', 'keine'), ('AN', 'andere')], max_length=4, verbose_name='Psychische Folgen')),
                ('koerperliche_folgen', models.CharField(choices=[('S', 'Schmerzen'), ('L', 'Lähmungen'), ('KR', 'Krankheit'), ('N', 'keine'), ('A', 'andere')], max_length=2, verbose_name='Körperliche Folgen')),
                ('finanzielle_folgen', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Finanzielle Folgen')),
                ('arbeitseinschraenkung', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Arbeitseinschränkung')),
                ('verlust_arbeitsstelle', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Verlust Arbeitsstelle')),
                ('soziale_isolation', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Soziale Isolation')),
                ('suizidalitaet', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Suizidalität')),
                ('keine_angabe', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, verbose_name='Falls zuvor kein Feld ausgefüllt')),
                ('beeintraechtigungen', models.TextField(blank=True, verbose_name='Dauerhafte körperliche Beeinträchtigungen')),
                ('weiteres', models.TextField(blank=True, verbose_name='Weiteres')),
                ('folgen_notizen', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Gewaltfolge',
                'verbose_name_plural': 'Gewaltfolgen',
            },
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='fall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gewalttaten', to='api.fall', verbose_name='Zugeordneter Fall'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.klientin', verbose_name='Klient:in'),
        ),
        migrations.CreateModel(
            name='Begleitung',
            fields=[
                ('begleitungs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anzahl_begleitungen', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl Begleitungen')),
                ('art_begleitung', models.CharField(choices=[('G', 'Gerichte'), ('P', 'Polizei'), ('R', 'Rechtsanwält:innen'), ('Ä', 'Ärzt:innen'), ('RM', 'Rechtsmedizin'), ('J', 'Jugendamt'), ('SA', 'Sozialamt'), ('JC', 'Jobcenter'), ('BS', 'Beratungsstellen'), ('FK', 'Frauen- und Kinderschutzeinrichtungen'), ('SS', 'spezialisierte Schutzeinrichtungen'), ('I', 'Interventionsstellen'), ('S', 'sonstige')], max_length=2, verbose_name='Art der Begleitung')),
                ('anzahl_verweisungen', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl Verweisungen')),
                ('art_verweisungen', models.CharField(blank=True, choices=[('G', 'Gerichte'), ('P', 'Polizei'), ('R', 'Rechtsanwält:innen'), ('Ä', 'Ärzt:innen'), ('RM', 'Rechtsmedizin'), ('J', 'Jugendamt'), ('SA', 'Sozialamt'), ('JC', 'Jobcenter'), ('BS', 'Beratungsstellen'), ('FK', 'Frauen- und Kinderschutzeinrichtungen'), ('SS', 'spezialisierte Schutzeinrichtungen'), ('I', 'Interventionsstellen'), ('S', 'sonstige')], max_length=2, verbose_name='Art der Verweisungen')),
                ('fall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begleitungen', to='api.fall', verbose_name='Zugeordneter Fall')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.klientin', verbose_name='Klient:in')),
            ],
            options={
                'verbose_name': 'Begleitung/Verweisung',
                'verbose_name_plural': 'Begleitungen/Verweisungen',
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('preset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preset_daten', models.JSONField(verbose_name='Ausgewählte Datenfelder')),
                ('preset_beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('filterKriterien', models.JSONField(verbose_name='Filterkriterien')),
                ('berechtigte', models.ManyToManyField(related_name='teilbare_presets', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigte Konten')),
                ('ersteller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ersteller:in')),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Presets',
            },
        ),
        migrations.CreateModel(
            name='Statistik',
            fields=[
                ('statistik_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statistik_titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('statistik_notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('zeitraum_start', models.DateField(verbose_name='Zeitraum Start')),
                ('zeitraum_ende', models.DateField(verbose_name='Zeitraum Ende')),
                ('ergebnis', models.FileField(upload_to='statistik_ergebnisse/', verbose_name='Ergebnisdatei')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Erstelldatum')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ersteller:in')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.preset', verbose_name='Preset')),
            ],
            options={
                'verbose_name': 'Statistik',
                'verbose_name_plural': 'Statistiken',
            },
        ),
    ]
