# Generated by Django 5.2.8 on 2026-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konto',
            options={'permissions': [('can_manage_users', 'Kann Benutzerkonten verwalten'), ('can_assign_roles', 'Kann Rollen zuweisen'), ('can_view_all_data', 'Kann alle Daten einsehen')], 'verbose_name': 'Benutzerkonto', 'verbose_name_plural': 'Benutzerkonten'},
        ),
        migrations.AlterModelOptions(
            name='preset',
            options={'permissions': [('can_share_preset', 'Kann Presets mit anderen teilen')], 'verbose_name': 'Preset', 'verbose_name_plural': 'Presets'},
        ),
        migrations.AlterModelOptions(
            name='statistik',
            options={'permissions': [('can_export_statistik', 'Kann Statistiken exportieren'), ('can_share_statistik', 'Kann Statistiken teilen')], 'verbose_name': 'Statistik', 'verbose_name_plural': 'Statistiken'},
        ),
    ]
