# Generated by Django 5.2.8 on 2026-01-03 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_konto_options_alter_preset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_datum',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum der Anfrage'),
        ),
    ]
