# Generated by Django 4.2.17 on 2026-01-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fix_anfrage_datum_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eingabefeld',
            fields=[
                ('feldID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name des Feldes')),
                ('typ', models.CharField(choices=[('Text', 'Text'), ('Zahl', 'Zahl'), ('Datum', 'Datum')], max_length=10, verbose_name='Datentyp')),
                ('wert', models.TextField(blank=True, null=True, verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Eingabefeld',
                'verbose_name_plural': 'Eingabefelder',
            },
        ),
    ]
