# Generated by Django 5.2.8 on 2026-01-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eingabefeld'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anfrage',
            options={'permissions': [('can_view_own_anfragen', 'Kann eigene Anfragen einsehen'), ('can_view_all_anfragen', 'Kann alle Anfragen einsehen')], 'verbose_name': 'Anfrage', 'verbose_name_plural': 'Anfragen'},
        ),
    ]
