# Generated by Django 5.2.8 on 2026-01-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_anfrage_view_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konto',
            options={'permissions': [('can_manage_users', 'Kann Benutzerkonten verwalten'), ('can_assign_roles', 'Kann Rollen zuweisen'), ('can_view_all_data', 'Kann alle Daten einsehen'), ('can_change_inactivity_settings', 'Kann Inaktivitäts-Einstellungen ändern')], 'verbose_name': 'Benutzerkonto', 'verbose_name_plural': 'Benutzerkonten'},
        ),
    ]
