# Generated by Django 5.2.8 on 2026-01-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_konto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klientin',
            options={'permissions': [('can_view_own_klienten', 'Kann eigene Klienten einsehen'), ('can_view_all_klienten', 'Kann alle Klienten einsehen')], 'verbose_name': 'Klient:in', 'verbose_name_plural': 'Klient:innen'},
        ),
    ]
