# Generated by Django 5.2.8 on 2026-01-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_klientin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klientin',
            options={'permissions': [('view_own_klientin', 'Kann eigene Klienten einsehen'), ('view_all_klientin', 'Kann alle Klienten einsehen')], 'verbose_name': 'Klient:in', 'verbose_name_plural': 'Klient:innen'},
        ),
    ]
