# Generated by Django 5.2.8 on 2026-01-07 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_klientin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientin',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
    ]
