# Generated by Django 5.2.8 on 2026-01-07 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_klientin_erstellt_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall',
            name='notizen',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='fall',
            name='startdatum',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Startdatum'),
        ),
        migrations.AddField(
            model_name='fall',
            name='status',
            field=models.CharField(choices=[('O', 'Offen'), ('L', 'Laufend'), ('A', 'Abgeschlossen'), ('G', 'Gelöscht')], default='O', max_length=2, verbose_name='Status'),
        ),
    ]
