# Generated by Django 5.2.8 on 2026-01-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fall_notizen_fall_startdatum_fall_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fall',
            options={'permissions': [('view_own_fall', 'Kann eigene Fälle einsehen'), ('view_all_fall', 'Kann alle Fälle einsehen')], 'verbose_name': 'Fall', 'verbose_name_plural': 'Fälle'},
        ),
    ]
