# Generated by Django 5.2.8 on 2026-01-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beratungstermin',
            options={'permissions': [('view_own_beratungstermin', 'Kann eigene Beratungstermine einsehen'), ('view_all_beratungstermin', 'Kann alle Beratungstermine einsehen')], 'verbose_name': 'Beratungstermin', 'verbose_name_plural': 'Beratungstermine'},
        ),
    ]
