# Generated by Django 5.2.8 on 2026-01-07 02:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_beratungstermin_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='begleitung',
            name='anzahl_begleitungen',
        ),
        migrations.RemoveField(
            model_name='begleitung',
            name='anzahl_verweisungen',
        ),
        migrations.RemoveField(
            model_name='begleitung',
            name='art_begleitung',
        ),
        migrations.RemoveField(
            model_name='begleitung',
            name='art_verweisungen',
        ),
        migrations.RemoveField(
            model_name='klientin',
            name='klient_dolmetschungsstunden',
        ),
        migrations.AddField(
            model_name='begleitung',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='begleitung',
            name='dolmetscher_stunden',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dolmetscher-Stunden'),
        ),
        migrations.AddField(
            model_name='begleitung',
            name='einrichtung',
            field=models.CharField(default='', max_length=255, verbose_name='Einrichtung (z.B. Polizei, Gericht)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='begleitung',
            name='notizen',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='beratungstermin',
            name='dauer',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dauer (Minuten)'),
        ),
        migrations.AddField(
            model_name='beratungstermin',
            name='dolmetscher_stunden',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dolmetscher-Stunden'),
        ),
        migrations.AddField(
            model_name='beratungstermin',
            name='status',
            field=models.CharField(choices=[('g', 'geplant'), ('s', 'stattgefunden'), ('a', 'ausgefallen')], default='g', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='beratungstermin',
            name='anzahl_beratungen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl Beratungen (Statistik)'),
        ),
        migrations.AlterField(
            model_name='beratungstermin',
            name='termin_beratung',
            field=models.DateTimeField(verbose_name='Zeitpunkt des Beratungstermins'),
        ),
    ]
