# Generated by Django 5.2.8 on 2026-02-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_begleitung_anzahl_begleitungen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eingabefeld',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Eingabefeld (Formular-Konfiguration)', 'verbose_name_plural': 'Eingabefelder (Konfiguration)'},
        ),
        migrations.RemoveField(
            model_name='eingabefeld',
            name='wert',
        ),
        migrations.AddField(
            model_name='eingabefeld',
            name='default_value',
            field=models.TextField(blank=True, null=True, verbose_name='Standardwert'),
        ),
        migrations.AddField(
            model_name='eingabefeld',
            name='label',
            field=models.CharField(default='', max_length=255, verbose_name='Beschriftung (Label)'),
        ),
        migrations.AddField(
            model_name='eingabefeld',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Liste von Objekten: [{'value': 'X', 'label': 'Y'}]", verbose_name='Optionen (für Select)'),
        ),
        migrations.AddField(
            model_name='eingabefeld',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Pflichtfeld'),
        ),
        migrations.AddField(
            model_name='eingabefeld',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='eingabefeld',
            name='name',
            field=models.CharField(help_text='Muss mit dem Modell-Feld übereinstimmen', max_length=255, verbose_name='Name des Feldes (Technisch)'),
        ),
        migrations.AlterField(
            model_name='eingabefeld',
            name='typ',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Zahl'), ('date', 'Datum'), ('select', 'Auswahl'), ('multiselect', 'Mehrfachauswahl')], max_length=20, verbose_name='Datentyp'),
        ),
    ]
