# Generated by Django 5.2.8 on 2026-02-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_eingabefeld_options_remove_eingabefeld_wert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eingabefeld',
            name='context',
            field=models.CharField(choices=[('anfrage', 'Anfrage'), ('fall', 'Fall')], default='anfrage', max_length=20, verbose_name='Kontext'),
        ),
    ]
