# Generated by Django 5.2.8 on 2026-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_eingabefeld_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eingabefeld',
            name='typ',
            field=models.CharField(choices=[('text', 'Text (kurz)'), ('textarea', 'Text (lang)'), ('number', 'Zahl'), ('date', 'Datum'), ('select', 'Auswahl'), ('multiselect', 'Mehrfachauswahl')], max_length=20, verbose_name='Datentyp'),
        ),
    ]
