# Generated by Django 5.2.8 on 2026-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_eingabefeld_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_weg',
            field=models.TextField(verbose_name='Anfrageweg (Freitext)'),
        ),
    ]
