# Generated by Django 5.2.8 on 2026-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_anfrage_anfrage_weg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_art',
            field=models.CharField(blank=True, choices=[('MS', 'medizinische Soforthilfe'), ('VS', 'vertrauliche Spurensicherung'), ('B', 'Beratungsbedarf'), ('R', 'rechtliche Fragen'), ('S', 'Sonstiges')], max_length=2, null=True, verbose_name='Anfrage Art'),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_ort',
            field=models.CharField(blank=True, choices=[('LS', 'Leipzig Stadt'), ('LL', 'Leipzig Land'), ('NS', 'Nordsachsen'), ('S', 'Sachsen (Andere)'), ('D', 'Deutschland (Andere)'), ('A', 'Ausland'), ('K', 'keine Angabe')], max_length=2, null=True, verbose_name='Anfrage Ort'),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_person',
            field=models.CharField(blank=True, choices=[('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('B', 'Betroffene:r'), ('AN', 'anonym'), ('qB', 'queer Betroffene:r'), ('qF', 'queer Fachkraft'), ('qA', 'queer Angehörige:r'), ('qAN', 'queer anonym'), ('FfB', 'Fachkraft für Betroffene'), ('AfB', 'Angehörige:r für Betroffene'), ('FFqB', 'Fachkraft für queere Betroffene'), ('AfqB', 'Angehörige:r für queere Betroffene')], max_length=4, null=True, verbose_name='Anfrage Person (wer)'),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_weg',
            field=models.TextField(blank=True, null=True, verbose_name='Anfrageweg (Freitext)'),
        ),
    ]
