# Generated by Django 5.2.8 on 2026-02-09 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_anfrage_anfrage_art_alter_anfrage_anfrage_ort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anfrage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
    ]
