# Generated by Django 5.2.8 on 2026-02-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_anfrage_created_at_anfrage_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preset',
            options={'permissions': [('can_share_preset', 'Kann Presets mit anderen teilen'), ('can_manage_presets', 'Kann Presets verwalten')], 'verbose_name': 'Preset', 'verbose_name_plural': 'Presets'},
        ),
        migrations.AlterModelOptions(
            name='statistik',
            options={'permissions': [('can_export_statistik', 'Kann Statistiken exportieren'), ('can_share_statistik', 'Kann Statistiken teilen'), ('can_view_statistics', 'Kann Statistiken einsehen')], 'verbose_name': 'Statistik', 'verbose_name_plural': 'Statistiken'},
        ),
        migrations.AddField(
            model_name='klientin',
            name='klient_migrationshintergrund',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], default='KA', max_length=3, verbose_name='Migrationshintergrund'),
        ),
    ]
