# Generated by Django 5.2.8 on 2026-02-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_preset_options_alter_statistik_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='status_mb',
            field=models.CharField(choices=[('A', 'Aktiv'), ('I', 'Inaktiv'), ('P', 'Ausstehend')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
