# Generated by Django 5.2.8 on 2026-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_konto_status_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientin',
            name='klient_pseudonym',
            field=models.CharField(blank=True, help_text='ACHTUNG: Hier keine Klarnamen verwenden! Nur Pseudonyme.', max_length=255, null=True, verbose_name='Pseudonym'),
        ),
    ]
