# Generated by Django 5.2.8 on 2026-02-17 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_klientin_klient_pseudonym'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='begleitung',
            options={'permissions': [('view_own_begleitung', 'Kann eigene Begleitungen einsehen'), ('view_all_begleitung', 'Kann alle Begleitungen einsehen')], 'verbose_name': 'Begleitung', 'verbose_name_plural': 'Begleitungen'},
        ),
        # 1. Remove old PK constraint by altering field to OneToOneField without primary_key=True (implicit)
        # Note: We must do this before adding the new PK field.
        migrations.AlterField(
            model_name='gewaltfolge',
            name='gewalttat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gewaltfolge', to='api.gewalttat', verbose_name='Zugehörige Gewalttat'),
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='arbeitseinschraenkung',
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='finanzielle_folgen',
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='koerperliche_folgen',
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='psychische_folgen',
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='soziale_isolation',
        ),
        migrations.RemoveField(
            model_name='gewaltfolge',
            name='verlust_arbeitsstelle',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_alter',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_anzahl_taeter_innen',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_anzahl_vorfaelle',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_anzeige',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_art',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_direktbetroffene_kinder',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_medizinische_versorgung',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_mitbetroffene_kinder',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_notizen',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_spurensicherung',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tat_zeitraum',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='tatort',
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='digitale_gewalt',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Digitale Gewalt'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='folge_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='gesundheitsschaedigung',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Gesundheitsschädigung'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='koerperliche_verletzung',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Körperliche Verletzung'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='oekonomische_gewalt',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Ökonomische Gewalt'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='psychische_gewalt',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Psychische Gewalt'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='sexualisierte_gewalt',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Sexualisierte Gewalt'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='soziale_gewalt',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Soziale Gewalt/Isolation'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='verfolgung_stalking',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Verfolgung/Stalking'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='plz_tatort',
            field=models.CharField(blank=True, max_length=5, verbose_name='PLZ Tatort'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_datum',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tatzeitpunkt'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_ort',
            field=models.CharField(choices=[('LS', 'Leipzig Stadt'), ('LL', 'Leipzig Land'), ('NS', 'Nordsachsen'), ('S', 'Sachsen (Andere)'), ('D', 'Deutschland (Andere)'), ('A', 'Ausland'), ('K', 'keine Angabe')], max_length=2, null=True, verbose_name='Tatort (Region)'),
        ),
        migrations.AddField(
            model_name='klientin',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Zusätzliche Felder'),
        ),
        migrations.AlterField(
            model_name='eingabefeld',
            name='context',
            field=models.CharField(choices=[('anfrage', 'Anfrage'), ('fall', 'Fall'), ('klient', 'Klient:in')], default='anfrage', max_length=20, verbose_name='Kontext'),
        ),
        migrations.AlterField(
            model_name='gewaltfolge',
            name='keine_angabe',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Falls zuvor kein Feld ausgefüllt'),
        ),
        migrations.AlterField(
            model_name='gewaltfolge',
            name='suizidalitaet',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Suizidalität'),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.klientin', verbose_name='Betroffene:r'),
        ),
    ]
