# Generated by Django 5.2.8 on 2026-02-17 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_begleitung_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallNotiz',
            fields=[
                ('notiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict, verbose_name='Inhalt (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor:in')),
                ('beratungstermin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_notizen', to='api.beratungstermin', verbose_name='Zugeordneter Termin')),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_notizen', to='api.fall', verbose_name='Fall')),
            ],
            options={
                'verbose_name': 'Fall-Notiz',
                'verbose_name_plural': 'Fall-Notizen',
                'ordering': ['-created_at'],
                'permissions': [('manage_fall_notizen', 'Kann Fall-Notizen verwalten')],
            },
        ),
    ]
