# Generated by Django 5.2.8 on 2026-02-18 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_fallnotiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallnotiz',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
    ]
