# Generated by Django 5.2.8 on 2026-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fallnotiz_datum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beratungstermin',
            old_name='notizen_beratung',
            new_name='notizen_beratung_old',
        ),
        migrations.AlterField(
            model_name='beratungstermin',
            name='notizen_beratung_old',
            field=models.TextField(blank=True, verbose_name='Notizen (Alt)'),
        ),
        migrations.AddField(
            model_name='beratungstermin',
            name='notizen_beratung',
            field=models.JSONField(blank=True, default=dict, verbose_name='Notizen (JSON)'),
        ),
    ]
