# Generated by Django 5.2.8 on 2026-02-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_data_migration_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beratungstermin',
            name='notizen_beratung_old',
        ),
    ]
