# Generated by Django 5.2.8 on 2026-02-18 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_beratungstermin_notizen_beratung_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallnotiz',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor:in'),
        ),
    ]
