# Generated by Django 5.2.8 on 2026-02-18 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_fallnotiz_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Globales Preset (für alle sichtbar)'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='berechtigte',
            field=models.ManyToManyField(blank=True, related_name='teilbare_presets', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigte Konten'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='ersteller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_presets', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller:in'),
        ),
    ]
