# Generated by Django 5.2.8 on 2026-02-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_preset_is_global_alter_preset_berechtigte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gewalttat',
            name='tat_direktbetroffene_kinder',
            field=models.PositiveIntegerField(default=0, verbose_name='Davon direkt betroffen'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_mitbetroffene_kinder',
            field=models.PositiveIntegerField(default=0, verbose_name='Mitbetroffene Kinder (gesamt)'),
        ),
    ]
