# Generated by Django 5.2.8 on 2026-02-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_gewalttat_tat_direktbetroffene_kinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gewalttat',
            name='tat_anzeige',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('E', 'noch nicht entschieden'), ('K', 'keine Angabe')], max_length=3, null=True, verbose_name='Wurde Anzeige erstattet?'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_art',
            field=models.TextField(blank=True, verbose_name='Art der Gewalt (Mehrfachauswahl)'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_spurensicherung',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Vertrauliche Spurensicherung?'),
        ),
    ]
