# Generated by Django 5.2.8 on 2026-02-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_gewalttat_tat_anzeige_gewalttat_tat_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gewaltfolge',
            name='arbeitseinschraenkung',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Arbeitseinschränkung/Arbeitsunfähigkeit'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='finanzielle_folgen',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Finanzielle Folgen'),
        ),
        migrations.AddField(
            model_name='gewaltfolge',
            name='verlust_arbeitsstelle',
            field=models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('KA', 'keine Angabe')], max_length=3, null=True, verbose_name='Verlust Arbeitsstelle'),
        ),
    ]
