# Generated by Django 5.2.8 on 2026-02-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_gewaltfolge_arbeitseinschraenkung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage',
            name='status',
            field=models.CharField(choices=[('AN', 'Anfrage'), ('TV', 'Termin vereinbart'), ('A', 'Abgeschlossen')], default='AN', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fall',
            name='status',
            field=models.CharField(choices=[('O', 'Offen'), ('L', 'Laufend'), ('A', 'Abgeschlossen')], default='O', max_length=2, verbose_name='Status'),
        ),
    ]
