# Generated by Django 5.2.8 on 2026-02-20 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_geloescht_status_add_anfrage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_retention_days', models.PositiveIntegerField(default=30, help_text='Wie lange sollen gelöschte Elemente im Papierkorb bleiben, bevor sie endgültig gelöscht werden?', verbose_name='Papierkorb Aufbewahrungsfrist (Tage)')),
            ],
            options={
                'verbose_name': 'Systemeinstellung',
                'verbose_name_plural': 'Systemeinstellungen',
                'permissions': [('manage_system_settings', 'Kann Systemeinstellungen verwalten')],
            },
        ),
        migrations.AddField(
            model_name='anfrage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_anfragen', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AddField(
            model_name='fall',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='fall',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_faelle', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='fall',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
    ]
