# Generated by Django 5.2.8 on 2026-02-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_systemsettings_anfrage_deleted_at_anfrage_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gewalttat',
            name='tat_taeter_beziehung',
            field=models.CharField(choices=[('P', 'Partner:in'), ('EXP', 'Partner:in ehemalig'), ('EF', 'Ehepartner:in / eingetragene:r Lebenspartner:in'), ('EFX', 'Ehepartner:in / eingetragene:r Lebenspartner:in ehemalig'), ('FAM', 'Familienangehörige (Eltern/Stiefeltern)'), ('VER', 'andere Verwandte'), ('NAH', 'soziales Nahfeld (Bekannte, Nachbarn, Kollegen)'), ('PRO', 'professionelle Beziehung (Lehrer, Arzt, Trainer etc.)'), ('HGM', 'häusliche Gemeinschaft (WG, Heim etc.)'), ('SON', 'sonstige Personen'), ('UNB', 'Unbekannte:r'), ('K', 'keine Angabe')], default='K', max_length=3, verbose_name='Beziehung zum Opfer'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='tat_taeter_geschlecht',
            field=models.CharField(choices=[('W', 'weiblich'), ('M', 'männlich'), ('D', 'divers'), ('U', 'unbekannt'), ('K', 'keine Angabe')], default='K', max_length=1, verbose_name='Täter-Geschlecht'),
        ),
    ]
