"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'DEFAULT_KEY_NUR_IM_NOTFALL')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ["localhost"] #TODO Added localhost here temporairily -> should be changed for production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Dritte-Anbieter-Apps (z.B. Django Rest Framework)
    'rest_framework', 
    'rest_framework.authtoken',
    'corsheaders',              
    'dj_rest_auth',
    'allauth',
    'allauth.account',

    'drf_spectacular',
    
    # Eigene Apps
    'api', # <-- Deine neue API-App!
]


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        
        # WICHTIG: 'db' ist der Name des Datenbank-Dienstes in der docker-compose.yml
        'HOST': os.environ.get('DB_HOST', 'db'), 
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Erzwingt JSON-Renderer als Standard für die API-Antworten
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    
    # Globale Permission-Einstellung (FR-05)
    # Standardmäßig ist der API-Zugriff nur für eingeloggte Nutzer erlaubt.
    # Dies kann später in einzelnen Views überschrieben werden.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Konfiguriert, wie Authentifizierungs-Header gelesen werden
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTH_USER_MODEL = 'api.Konto'

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'app-auth',         # Name des Access-Token Cookies
    'JWT_AUTH_REFRESH_COOKIE': 'app-refresh-token',
    'JWT_AUTH_HTTPONLY': True,                # JavaScript kann Cookie nicht lesen (Sicherheit!)
    'SESSION_LOGIN': False,
    'USER_DETAILS_SERIALIZER': 'api.serializers.KontoSerializer', # Damit wir Vornamen/Rolle zurückkriegen
}

REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'api.serializers.CustomLoginSerializer',
    'USER_DETAILS_SERIALIZER': 'api.serializers.KontoSerializer',
}

# Einfaches JWT Setup (keine E-Mail Verifizierung für den Anfang)
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_USER_MODEL_EMAIL_FIELD = 'mail_mb'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# --- CORS (Damit Next.js auf Port 3000 zugreifen darf) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True # Wichtig für Cookies!
CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]



if DEBUG:
    # In development, allow embedding from anywhere (e.g., Next.js on localhost:3000)
    X_FRAME_OPTIONS = 'ALLOWALL'

    # Also helpful for dev: Disable the middleware entirely if headers are stubborn
    MIDDLEWARE.remove('django.middleware.clickjacking.XFrameOptionsMiddleware')

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
    ]
    CORS_ALLOW_CREDENTIALS = True # Wichtig für Cookies!
    CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "http://localhost:8000"]


else:
    # In production, be strict!
    X_FRAME_OPTIONS = 'SAMEORIGIN'

    CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    ]
    CORS_ALLOW_CREDENTIALS = True # Wichtig für Cookies!
    CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]